### ISSUE TITLE
Support inserting elements in an include file to an array/map

### ISSUE THREAD

**Issue by matthewrmshin** [JCSDA-internal/yamlprocessor#11]
Consider this use case:

```yaml
- filter: A
  options: ...
# ... need to insert many filters from an include file here, e.g., a station list file
- filter: Z
  options: ...
```

There is likely to be similar use cases for map/object? E.g.,

```yaml
people:
    Alice:
        greet_phrase: Hello
        # ... insert many key-value elements from an include file here
        is_happy_today: true
