### ISSUE TITLE
Questions over processing yaml for met office ocean runs

### ISSUE THREAD

**Issue by twsearle** [JCSDA-internal/yamlprocessor#33]
## Description

Help us understand discrepancies with lists of strings after being processed by yamlprocessor.

@adammaycock will be providing a stripped down example of the issue in due course.

**Comment by adammaycock** [comment]
I believe this is responsible for differences in ocnd results...

Input yaml:

```
    - filter: Ship Track Check
      where:
      - variable:
          name: MetaData/stationIdentification
        is_not_in: ['', '0', 'SHIP', '*** MISSING ***', 'MISSING*']
      unit testing mode: false
```

Output yaml

```
- filter: Ship Track Check
  where:
  - variable:
      name: MetaData/stationIdentification
    is_not_in:
    - ''
    - '0'
    - SHIP
    - '*** MISSING ***'
    - MISSING*
  unit testing mode: false
```

the significant difference being the loss of quotes around `SHIP` and/or `MISSING*`
